### ISSUE TITLE
RangeError: value of 'position' is out of range

### ISSUE THREAD

**Issue by rcompier** [AtomMaterialUI/mtslack#158]
### Describe the bug
Applying mtslack on windwos 10 gives an error:

`UnhandledPromiseRejectionWarning: RangeError - the value of 'position' is out of range. Must be an integer, received NaN`

### To Reproduce
1. Open CMD
2. Run mtslack
3. Apply tweaks
4. Set default location
5. See error

### Expected behavior
Mtslack should copy the config to the clipboard to paste in devtools.

### Screenshots
![image](https://user-images.githubusercontent.com/21107109/158126678-68967631-010c-49e9-8abd-8c0af5af8b65.png)

### Desktop
 - OS: Windows 10 - 21h2 (19044.1566)

**Comment by mallowigi** [comment]
Haven't checked on windows but please make sure you're using node v16+

**Comment by mallowigi** [comment]
@Saghen  ?

**Comment by rcompier** [comment]
With updating node to v16+, the code doesn't crash anymore.

However, it seems to not affect slack, neither in regular or admin mode.

**Comment by Saghen** [comment]
Able to reproduce on my end as well. I'll take a look in the next couple of days, sorry about this

**Comment by Saghen** [comment]
@mallowigi The fix I posted I had to do for the fork of asar also fixed the issue for windows
https://github.com/mallowigi/mtslack/pull/155

**Comment by mallowigi** [comment]
Have you posted a pr in asar? I'll publish a version if you assure it's ready.

**Comment by Saghen** [comment]
It works on both my systems on fresh slack installs but it would be worth it checking on your system too

**Comment by Saghen** [comment]
@mallowigi Following up on this. Was the fix I posted in #155 added to the asar package. If not, do you need anything from me to get it out? I can post a PR but it's just that few lines that needed changing

**Comment by mallowigi** [comment]
Frankly I don't want to invest in this project anymore. The current version with the console code is good enough and I don't want to bother trying to improve especially due to the limitations that I couldn't find a good fix against.

I will keep on adding new css rules when they are added but apart from that I will not publish newer versions.
