### ISSUE TITLE
Disable animation in Slack Tweaks not working

### ISSUE THREAD

**Issue by chrisob55** [AtomMaterialUI/mtslack#229]
**Describe the bug**

**To Reproduce**
1. Go to 'Slack Tweaks'
2. Click on 'disable animations'
3. Animations still happen

**Expected behavior**
Animations should stop

**Desktop (please complete the following information):**
 - MacOS Version 4.31.155
- mtslack v29.0.0

**Additional context**
In general, the animations are really buggy so I'd really like to be able to turn them off

**Comment by chrisob55** [comment]
Hi @mallowigi Yes it was through the Slack tweaks window. Toggling on/off doesn't seem to do anything

**Comment by mallowigi** [comment]
That's because this setting window actually controls the settings that appear in the title bar. You have to click on the corresponding icon to toggle them.

**Comment by toclean** [comment]
Can repro.

- Load slack with modifications (I'm using the darker theme for instance)
- Disable animations by clicking the '@' symbol at the top of the window.
- Switch to a different "tab" (i.e. DMs)
- Switch back
- Animations are enabled again

**Comment by mallowigi** [comment]
It's a different issue. It's a general issue with the new "tabs". You can see that switching to DMs or Activity for example also switches the theme, the font etc.

I have yet to find the cause of this. But if you stay on the Home tab, switching off the animations should work.

**Comment by toclean** [comment]
Oh okay gotcha
