### ISSUE TITLE
Script doesn't run in terminal

### ISSUE THREAD

**Issue by elgorditosalsero** [AtomMaterialUI/mtslack#233]
**Describe the bug**

When running `sudo mtslack` the script doesn't run.

**To Reproduce**

1. Open the terminal
2. Run `sudo mtslack`

**Expected behavior**

The script should run as usual

**Screenshots**

https://github.com/mallowigi/mtslack/assets/65770455/d1e2e6e8-e9e4-4686-9d76-f6df0f95876e

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version 13.4.1 

**Additional context**

Node version: 18.15.0

**Comment by mallowigi** [comment]
try without sudo

**Comment by elgorditosalsero** [comment]
@mallowigi same result 😢 

https://github.com/mallowigi/mtslack/assets/65770455/d40488c2-c3c6-45b8-9d1d-a77bf59bcf9c

**Comment by mallowigi** [comment]
What is your version of mtslack? Maybe try to reinstall it? `npm i -g mtslack`

**Comment by mallowigi** [comment]
Well I don't know what to tell you. It works in my machine.

Maybe try in different terminals ?

**Comment by elgorditosalsero** [comment]
I tried to switch to `bash` from `zsh` as a shell, but the issue is persisting.

I have te shame behavior both with `iTerm2` and standard MacOS terminal.

![Screenshot 2023-07-13 at 15 17 16](https://github.com/mallowigi/mtslack/assets/65770455/a99e0ee3-1f95-407b-ba38-84fedebd8b92)
![Screenshot 2023-07-13 at 15 16 19](https://github.com/mallowigi/mtslack/assets/65770455/43f0a08f-0160-46bd-ba9c-315f82a041a4)

**Comment by elgorditosalsero** [comment]
Me too, and I'm still trying to debug why it's sending `SIGINT`
